spring:
  datasource:
    username: root
    password: 11037
    url: jdbc:mysql://localhost:3306/crafting_recipes
  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

springdoc:
  api-docs:
    path: /api-docs

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: ERROR
  file:
    name: crafting.log

# Swagger UI path -> http://localhost:8080/swagger-ui/index.html
# springdoc.api-docs.path is renaming of the OG path for the JSON Swagger
# changing it to this -> http://localhost:8080/api-docs
